-- Tabla que registra cada viaje que realiza un monopatín del sistema
-- Un viaje tiene: horarios, paradas inicial y final, km recorridos, tarifa aplicada y datos del usuario.

CREATE TABLE viaje (
    id BIGSERIAL PRIMARY KEY,
    id_usuario BIGINT NOT NULL,
    id_cuenta BIGINT NOT NULL,
    monopatin_id BIGINT NOT NULL,
    fecha_hora_inicio TIMESTAMP NOT NULL,
    fecha_hora_fin TIMESTAMP,
    parada_inicio_id BIGINT NOT NULL,
    parada_fin_id BIGINT,
    km_recorridos DECIMAL(10,2),
    tarifa_id BIGINT,
    tiempo_total_minutos INT,
    pausa_total_minutos INT,
    costo_total DECIMAL(10,2)



);
CREATE TABLE viaje
(
    costo_total numeric(38,2),
    km_recorridos numeric(38,2),
    pausa_total_minutos integer,
    tiempo_total_minutos integer,
    fecha_hora_fin timestamp(6) without time zone,
    fecha_hora_inicio timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_cuenta bigint NOT NULL,
    id_usuario bigint NOT NULL,
    monopatin_id bigint NOT NULL,
    parada_fin_id bigint,
    parada_inicio_id bigint NOT NULL,
    tarifa_id bigint,
    CONSTRAINT viaje_pkey PRIMARY KEY (id)
    );
